### ISSUE TITLE
Проблема с баллами

### ISSUE THREAD

**Issue by DenisKhrychev** [AlexVin-Dev/Yukon-Union#32]
** Опишите ошибку**
1.)Проблема с начислением баллов за рейсы
2.) Есть рейсы которые, вроде как приняты, и имя диспетчера в списке стоит, но он подсвечен серым(как не проверенный), и в диспетчерской ни в одном списке он не значится
3.) Есть рейсы у которых вообще пропала масса или наименование перевозимого груза...
(если необходимо могу предоставить полный список проблемных рейсов, через Дискорд)

** Воспроизводить**
Шаги по воспроизведению поведения:
1. Перейдите в раздел "Диспетчерская-Новые-Обычные"
2. Нажмите на "Подробнее" и проверьте правильность указанных данных, если данные верны, нажмите "Принять"
3. Зайдите в профиль водителя отчет которого Вы принимали и посмотрите раздел "Список рейсов"
4. проблема возникала при случайных условиях и у других водителей, но не в таком количестве

** Ожидаемое поведение**
Зачисление баллов из расчета (пробег,км/400 (насколько помню))

** Скриншоты**
![image](https://user-images.githubusercontent.com/43922879/143730334-0b36ab3f-a19b-48e9-8a91-57a84fa5db16.png)

** Рабочий стол (пожалуйста, заполните следующую информацию):**
- ОС: [Win7 SP1 домашняя расширенная]
- Браузер [chrome]
- Версия [Версия 96.0.4664.45 (Официальная сборка), (64 бит)]

** Смартфон (пожалуйста, заполните следующую информацию):**
- - Устройство: [отсутствует]
- ОС: [например, iOS8.1]
- Браузер [например, стандартный браузер, safari]
- Версия [например, 22]

** Дополнительный контекст**
Добавьте сюда любой другой контекст, касающийся проблемы.

[YKN-U] Denis [152RUS]

**Comment by AlexVin-Dev** [comment]
Проблема исправлена. Все остальным пересчитаю баллы в ручную

**Comment by AlexVin-Dev** [comment]
Готово
