### ISSUE TITLE
Диспетчерская, приём отчетов

### ISSUE THREAD

**Issue by DenisKhrychev** [AlexVin-Dev/Yukon-Union#4]
Вопрос, есть ли возможность отслеживания того просматривается отчет диспетчером в данный момент или нет?, если есть, то можно ли сделать какую-либо пометку на станицах со списками рейсов, а то иногда получается что одновременно просматривается один отчет несколькими диспетчерами и, соответственно отправляется на редактирование или принимается несколько раз...
![image](https://user-images.githubusercontent.com/43922879/140266232-96056662-9239-4405-a4b4-e39df79bbfe5.png)

**Comment by AlexVin-Dev** [comment]
Да есть такая возможность сделать. Как найду больше времени - **сделаю**

**Comment by AlexVin-Dev** [comment]
Добавил одну функцию, которая не должна позволить принимать рейсы, которые уже приняты.
Если будет не правильно работать сообщите.
